### ISSUE TITLE
Resolve Minor Security Issues Reported by Horusec

### ISSUE THREAD

**Issue by rauljordan** [OffchainLabs/prysm#9975]
# 💎 Issue

### Background

@uncdr recently included the Horusec security scanning tool for open source projects in #9880, and it has found a few issues we should aim to resolve soon. See the failing CI build [here](https://github.com/prysmaticlabs/prysm/runs/4170016424?check_suite_focus=true) for a full list of problems discovered by Horusec. Most of these are minor fixes and dependency updates. We should resolve so that we can safely merge #9880 and have green PRs after that. This is a tracking issue to resolve the problems reported in #9880 and can be closed once those issues have been addressed. This is a good first issue for contributors.

**Comment by mfiumara** [comment]
Hey I was trying to pick this up and ran the horusec check on develop. The build issues are not available anymore in the linked CI build, you can check my pastebin here for the list of issues: https://pastebin.com/VqKCYC6A

I tried some dependencies but I'm not familiar with bazel, getting the following error:

```
➜  prysm git:(horusec-scanner) ✗ bazelisk run //:gazelle -- update-repos -from_file=go.mod                                          
INFO: Repository llvm_toolchain instantiated at:
  /home/mattia/repos/prysm/WORKSPACE:29:15: in <toplevel>
Repository rule llvm_toolchain defined at:
  /home/mattia/.cache/bazel/_bazel_mattia/d3471c3b3fa4133093f049a701cbc11f/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/home/mattia/.cache/bazel/_bazel_mattia/d3471c3b3fa4133093f049a701cbc11f/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/home/mattia/.cache/bazel/_bazel_mattia/d3471c3b3fa4133093f049a701cbc11f/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
                fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
Please ensure file name is correct.
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/home/mattia/.cache/bazel/_bazel_mattia/d3471c3b3fa4133093f049a701cbc11f/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/home/mattia/.cache/bazel/_bazel_mattia/d3471c3b3fa4133093f049a701cbc11f/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 177, column 13, in download_llvm_preconfigured
                fail("Unknown LLVM release: %s\nPlease ensure file name is correct." % basename)
Error in fail: Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
Please ensure file name is correct.
ERROR: no such package '@llvm_toolchain//': Unknown LLVM release: clang+llvm-10.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
Please ensure file name is correct.
INFO: Elapsed time: 0.215s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Any help appreciated I can try to move this forward.

**Comment by rkapka** [comment]
Closing in favor of https://github.com/OffchainLabs/prysm/issues/13791
